### ISSUE TITLE
Flint tools issue

### ISSUE THREAD

**Issue by volcano010** [TheQuantumGeneral/PowerCreepRevival#43]
I cant craft any flint tools, and can i suggest a early recipe for get flint?

Modpack: Power Creep Revival
Version: 0.4

**Comment by victor4k** [comment]
Tested. Axe, shovel and Pickaxe all working with flint.

**Comment by victor4k** [comment]
After more info found to be staging problem.
flint tools gated to stage1

**Comment by TheQuantumGeneral** [comment]
Version 0.5 now pending approval on Curseforge fixes this issue. 

**Version: 0.5**

**Configs:**
N/A

**Scripts:**
-Added recipe for Flint (2 gravel, shapeless recipe, gives 3)
-Fixed stone tools being uncraftable till Age 1
-You now spawn with a Quest Book

**Mods:**
-Added Old Java Warning mod (Minecraft/Twitch launcher come packaged with an old unstable version of Java)
